### ISSUE TITLE
How do I obtain other cutscenes not included in the current version of the game?

### ISSUE THREAD

**Issue by Articomb** [ToaHartor/GI-cutscenes#101]
I dont think every cutscene in the game is in the game files, notably older version cutscenes. What are the other options to get them?

**Comment by mchubby** [comment]
You can track [reddit posts by u/SingularityHRT](https://www.reddit.com/user/SingularityHRT/submitted/) for previous or upcoming official client links. Here's a paste for convenience: https://pastebin.com/3YDuaVdg

I then use visidata, a Python text ui program to open remote zip URLs (just reads the 'central directory' e.g. file listing of the archive).

The tool lets you pick which video files contained in the archive to extract, without having to download the whole remote file. Saves bandwidth and disk space. (View Menu > Resize columns, move cursor then File > extract > ...)

The other option is to download the (inceremental) diff zips between game versions in the reddit posts.

**Comment by Articomb** [comment]
Goated

Thank you very much!

**Comment by JRSKelvin** [comment]
Wow, thank you @Articomb and @mchubby for the question and explanation. I also have saved all version download links from 1.3 to 3.7. But you even found earlier versions. Yes, each patch will delete and add new cutscenes when update through the launcher to save storage space, especially event-limited cutscenes like Lanter Rite, Golden Apple Archipelago, etc. But it can be found in the previous or diff zip files.

**Comment by Unknow-404** [comment]
See #104
