### ISSUE TITLE
Something go to wrong

### ISSUE THREAD

**Issue by Moshimoxi** [ToaHartor/GI-cutscenes#107]
Here is the Traceback. Is the key wrong?

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "eel\__init__.py", line 303, in _process_message
KeyError: 'value'
2023-07-17T02:26:25Z <Greenlet at 0x1630eaa6ae0: _process_message({'return': 47.45104701764378, 'status': 'error', ', <geventwebsocket.websocket.WebSocket object at 0x0)> failed with KeyError

**Comment by JohnSlaughter** [comment]
I get this error too.  It still rips from Genshin fine, but then sits for about 2 minutes before merging the mp4.  still works, just takes forever.  Would like to get rid of that timeout.

**Comment by JohnSlaughter** [comment]
FYI, here is the app logs:

Output folder : D:\Genshin Impact Videos
Finding encryption key for Ambor_Readings.usm...
key1=D53F3E0B key2=00000000
Demuxing Ambor_Readings.usm : extracting video and audio...
Converting Ambor_Readings_2.hca to wav...
Converting Ambor_Readings_3.hca to wav...
Converting Ambor_Readings_1.hca to wav...
Converting Ambor_Readings_0.hca to wav...
Extraction completed !
924ms elapsed

Starting ffmpeg
Working ffmpeg...
Input #0, ivf, from 'D:/Genshin Impact Videos\Ambor_Readings.m2v':
Duration: 00:01:26.33, start: 0.000000, bitrate: 9663 kb/s
Stream #0:0: Video: vp9 (Profile 0) (VP90 / 0x30395056), yuv420p(tv, smpte170m/unknown/unknown), 1920x1080, 30 tbr, 30 tbn
[aist#1:0/pcm_s16le @ 000001f6553d7cc0] Guessed Channel Layout: stereo
Input #1, wav, from 'D:/Genshin Impact Videos\Ambor_Readings_1.wav':
Duration: 00:01:27.34, bitrate: 1536 kb/s
Stream #1:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 2 channels, s16, 1536 kb/s
Stream mapping:
Stream #0:0 -> #0:0 (vp9 (native) -> h264 (libx264))
Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 000001f6553d4a40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 000001f6553d4a40] profile High, level 4.0, 4:2:0, 8-bit
[libx264 @ 000001f6553d4a40] 264 - core 164 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'D:/Genshin Impact Videos\Ambor_Readings.mp4':
Metadata:
encoder         : Lavf60.15.101
Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, smpte170m/unknown/unknown, progressive), 1920x1080, q=2-31, 30 fps, 15360 tbn
Metadata:
encoder         : Lavc60.30.102 libx264
Side data:
cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s
Metadata:
encoder         : Lavc60.30.102 aac

**_<< Here's where it dies for a LONG time.  No CPU activity.  >>_**

frame= 2522 fps= 16 q=29.0 size=   33792kB time=00:01:25.82 bitrate=3225.5kbits/s speed=0.554x
[out#0/mp4 @ 000001f653a0a080] video:32686kB audio:1371kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.274339%
[libx264 @ 000001f6553d4a40] consecutive B-frames:  5.0%  4.7%  7.5% 82.8%
[libx264 @ 000001f6553d4a40] mb I  I16..4: 31.8% 57.7% 10.5%
[libx264 @ 000001f6553d4a40] mb P  I16..4:  8.5% 15.7%  1.1%  P16..4: 36.1%  8.8%  4.0%  0.0%  0.0%    skip:25.8%
[libx264 @ 000001f6553d4a40] mb B  I16..4:  1.0%  1.3%  0.0%  B16..8: 33.9%  1.8%  0.2%  direct: 1.8%  skip:60.0%  L0:45.1% L1:51.3% BI: 3.5%
[libx264 @ 000001f6553d4a40] 8x8 transform intra:60.4% inter:83.9%
[libx264 @ 000001f6553d4a40] coded y,uvDC,uvAC intra: 24.3% 48.6% 11.0% inter: 6.6% 13.6% 0.6%
[libx264 @ 000001f6553d4a40] i16 v,h,dc,p: 29% 32% 13% 26%
[libx264 @ 000001f6553d4a40] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 19% 31%  3%  5%  4%  5%  2%  3%
[libx264 @ 000001f6553d4a40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 23% 20% 19%  4% 11%  7%  9%  4%  3%
[libx264 @ 000001f6553d4a40] i8c dc,h,v,p: 53% 24% 20%  3%
[libx264 @ 000001f6553d4a40] Weighted P-Frames: Y:14.7% UV:13.5%
[libx264 @ 000001f6553d4a40] ref P L0: 68.9%  7.9% 17.0%  5.9%  0.3%
[libx264 @ 000001f6553d4a40] ref B L0: 91.0%  7.3%  1.6%
[libx264 @ 000001f6553d4a40] ref B L1: 96.4%  3.6%
[libx264 @ 000001f6553d4a40] kb/s:3101.43
[aac @ 000001f655a890c0] Qavg: 1362.376
Merging complete!

**Comment by JohnSlaughter** [comment]
SOLVED...   it's ffmpeg.   Go grab a build from like mid 2022 and it works fine.   The latest is what hangs it.

**Comment by ToaHartor** [comment]
Alright, marking it as solved then.
