### ISSUE TITLE
Error after changing versions.json

### ISSUE THREAD

**Issue by QKD2** [ToaHartor/GI-cutscenes#12]
![image](https://user-images.githubusercontent.com/51942604/172013509-e04c6918-cdcf-4c3e-bd56-af67304cef1a.png)

**Comment by ToaHartor** [comment]
Since the format changed for 2.7+, I'll be releasing a new version very soon !

**Comment by ToaHartor** [comment]
Fixed with the [new release](https://github.com/ToaHartor/GI-cutscenes/releases/tag/v0.3.0) 👀
