### ISSUE TITLE
ETA on 4.2 Keys?

### ISSUE THREAD

**Issue by LumonosityMSU** [ToaHartor/GI-cutscenes#123]
Hi! Appreciate the work you all do here very, very much. I was just curious on how long it will take for 4.2 keys to be released since the pre-download has been out for a couple of days. Unsure if that is able to help speed up the key obtaining process. I run a Genshin Footage Bank preserving all cutscenes including limited time event ones. You guys are awesome, appreciate what you do! <3

Update: I have been doing research here and on various forms and have learned that the keys are sent via the servers when meeting certain criteria in the game, such as meeting certain quests. Does anyone know where these keys are stored in the game files, or if they are stored locally at all? Unsure if they are only sent via packets for the game for a temporary amount of time before being erased. I'm no expert with CS and coding, my expertise is Cybersecurity and Networking.

**Comment by shimiandezhu66** [comment]
> Hi! Appreciate the work you all do here very, very much. I was just curious on how long it will take for 4.2 keys to be released since the pre-download has been out for a couple of days. Unsure if that is able to help speed up the key obtaining process. I run a Genshin Footage Bank preserving all cutscenes including limited time event ones. You guys are awesome, appreciate what you do! <3
> 
> Update: I have been doing research here and on various forms and have learned that the keys are sent via the servers when meeting certain criteria in the game, such as meeting certain quests. Does anyone know where these keys are stored in the game files, or if they are stored locally at all? Unsure if they are only sent via packets for the game for a temporary amount of time before being erased. I'm no expert with CS and coding, my expertise is Cybersecurity and Networking.

How amazing the main plot I played,I wanna get the 4.2keys too.....
This can only be obtained by grabbing online packets when they pass the plot. You can only wait for their reply.

**Comment by ikenxuan** [comment]
Can you tell me about this site, I want to check it out
能告诉我这个网站吗，我想看看
