### ISSUE TITLE
Internal error decrypting 4.1 Fontaine cutscenes

### ISSUE THREAD

**Issue by Caelum008** [ToaHartor/GI-cutscenes#124]
> [vist#0:0/vp9 @ 000002a16547c4c0] Error submitting packet to decoder: Invalid data found when processing input
> Last message repeated 18 times
> [vist#0:0/vp9 @ 000002a16547c4c0] A decoder returned an unexpected error code. This is a bug, please report it.
> [vist#0:0/vp9 @ 000002a16547c4c0] Error processing packet in decoder: Internal bug, should not have happened
> [vist#0:0/vp9 @ 000002a16547c4c0] Decoder thread returned error: Internal bug, should not have happened

**Comment by ToaHartor** [comment]
Try to update the file containing the keys (`versions.json`), as it didn't contain version 4.1 keys yet.

**Comment by Caelum008** [comment]
> Try to update the file containing the keys (`versions.json`), as it didn't contain version 4.1 keys yet.

ohh. it worked. thank you so much.
