### ISSUE TITLE
Update For 4.3 Keys

### ISSUE THREAD

**Issue by JRSKelvin** [ToaHartor/GI-cutscenes#133]

**Comment by shy-fox** [comment]
The keys file only contains up to 3.4 or so

**Comment by Jerry12228** [comment]
Does anyone know how to use this

I successfully compiled it, but I don't know how it should work with Genshin Impact
![image](https://github.com/ToaHartor/GI-cutscenes/assets/86408775/ce79920d-4790-4672-bc3e-19587342011c)
