### ISSUE TITLE
some values for V4.4 pre-downlad package are missing

### ISSUE THREAD

**Issue by HRB-YuPai** [ToaHartor/GI-cutscenes#137]
Hello developer.

When I try to demux the new video usm files in the pre-download package for V4.4, it shows me no values (key, version) found in the versions.json. could you please teach me how to find the required values so that I could demux it?

In appreciation

**Comment by gszshdzz** [comment]
#8 
You can only get the key when you play the videos in the game

**Comment by HRB-YuPai** [comment]
so how to get it when the video is playing in the game

**Comment by 360NENZ** [comment]
4.4 versions.json: [Asayu233's repo](https://raw.githubusercontent.com/Asayu233/GI-cutscenes/main/versions.json)
