### ISSUE TITLE
Update For 4.4 Keys

### ISSUE THREAD

**Issue by JRSKelvin** [ToaHartor/GI-cutscenes#138]

**Comment by 360NENZ** [comment]
Here: [Asayu233's repo](https://raw.githubusercontent.com/Asayu233/GI-cutscenes/main/versions.json)

**Comment by JRSKelvin** [comment]
Thank You @360NENZ @Asayu233, But the key is still unavailable yet, we need to wait for the cutscene release in-game to be able retrieve the key

**Comment by jzfzzzz** [comment]
> Here: [Asayu233's repo](https://raw.githubusercontent.com/Asayu233/GI-cutscenes/main/versions.json)

![image](https://github.com/ToaHartor/GI-cutscenes/assets/107303455/acac6a33-afca-416b-b807-932b3d190dd1)
你好，我用你这个解析是解析出来的，但是视频播放是像截图里的一样，声音全是噪音，请问这个是怎么一回事啊

**Comment by BUnipendix** [comment]
密钥还没有，用0占位的，等这个人提交

**Comment by JRSKelvin** [comment]
对，跟 @BUnipendix 所说，密钥还没有，@jzfzzzz 大概要到海灯节过了才有（平常是在农历新年前一天，再加上几天获得密码）
