### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by JPS46225** [ToaHartor/GI-cutscenes#14]
Hi

I was wondering whether it would be possible for you to support macOS with this tool given that a Linux version is available.

While I am aware that there is no game client for Genshin Impact on macOS, I would still like to be able to do work related to the scope of this project using this OS.

Thanks

**Comment by ToaHartor** [comment]
I don't have a computer running macOS, however .NET has a compilation option for macOS. Can you try [this](https://github.com/ToaHartor/GI-cutscenes/files/8873995/GICutscenes_osx-x64.zip) build please ? (I can't upload the standalone build, as its size exceeds the maximum allowed by the comment section, so you should have dotnet on your machine for the framework dependent one). If it works, then I'll be able to add them to the last release 👀

**Comment by ToaHartor** [comment]
*taking notes* Alright, and can you confirm these builds work ? So that I can add them to the release page 👀

**Comment by JPS46225** [comment]
> is there a such thing called "Terminal.app"?
> I remember it can run linux programs directly

Linux binaries use a different format.

**Comment by JPS46225** [comment]
> To build GI-cutscenes on Mac, use the following command:
> 
> `dotnet publish -c Release -r osx.12-arm64 -p:PublishSingleFile=true --self-contained false` (Apple Silicon)
> 
> `dotnet publish -c Release -r osx.12-x86-64 -p:PublishSingleFile=true --self-contained false` (Intel)
> 
> You may also need to change the macOS version in the command. As for .Net SDK, you can either use the one shipped with VS, or you can install it by yourself.

Thanks :)

**Comment by ToaHartor** [comment]
Added these two runtimes in the building script, will close on 0.4.0 release
