### ISSUE TITLE
Getting Dialogue only (Voiceover)

### ISSUE THREAD

**Issue by ft-scobra** [ToaHartor/GI-cutscenes#144]
I just wanted to know if its possible to only output the voice part of the cutscenes. i.e., No music, just voice dialogue in audio format. I know the game can do it for quest dialogue but is it possible for the cutscenes?

**Comment by ToaHartor** [comment]
There is only one track for the audio of the cutscene (per audio language), therefore it is not possible to separate the voice dialogue from the rest.

**Comment by ft-scobra** [comment]
Alright Thanks.
