### ISSUE TITLE
5.0 keys!

### ISSUE THREAD

**Issue by jzfzzzz** [ToaHartor/GI-cutscenes#163]
Huoshen is really handsome, and the actions you shared with 5.0key are also handsome

**Comment by Jirehlov** [comment]
You can actually speak Chinese if you don't speak English, lol. Huoshen -> Pyro Archon

**Comment by jzfzzzz** [comment]
> You can actually speak Chinese if you don't speak English, lol. Huoshen -> Pyro Archon

好的，还是谢谢大佬无偿提供这些key

**Comment by huaxianmfs** [comment]
"Video_Reunion_50"的key是0，在.json文件里加上这个就行了

**Comment by jzfzzzz** [comment]
> "Video_Reunion_50"的key是0，在.json文件里加上这个就行了

key一般不可能是0吧

**Comment by Deiloproxide** [comment]
> Huoshen is really handsome, and the actions you shared with 5.0key are also handsome

It is "Mavuika" or  "the Pyro God" , not "HuoShen" .
And the key is really 0






算了，我也不装foreigner了，哈哈
