### ISSUE TITLE
please update 5.0.0  usm keys

### ISSUE THREAD

**Issue by HRB-YuPai** [ToaHartor/GI-cutscenes#165]
It has been nearly 1 month since 5.0 update, but there is still no 5.0 keys. Does anyone could update 5.0 keys in json or under this issue? much appreciation

**Comment by gszshdzz** [comment]
#164 
please check  PRs first

**Comment by HRB-YuPai** [comment]
我去，好好好，我说怎么主文件没更新，是tor 忘了还是咋回事

**Comment by gszshdzz** [comment]
一般都会在快更新下一个版本才合并吧，况且还差一个没有（Video_Reunion_50），内容未知（5.0我玩的少）

**Comment by gszshdzz** [comment]
https://github.com/ToaHartor/GI-cutscenes/issues/163#issuecomment-2336632581
这个的key是0

**Comment by ToaHartor** [comment]
Oh yes I forgot to merge the PR, should be resolved now

**Comment by jzfzzzz** [comment]
> Oh yes I forgot to merge the PR, should be resolved now

非常感谢
