### ISSUE TITLE
how to get GI5.1 key from file "26236578.blk"?

### ISSUE THREAD

**Issue by Deiloproxide** [ToaHartor/GI-cutscenes#173]
I found this blk file in the content "Genshin Impact\Genshin Impact Game\YuanShen_Data\StreamingAssets\VideoAssets".

I opened it in a text editor and saw many text pieces very similar to the "version.json" , but some of them were encrypted.

We can easily get some of its key in the older version of GI , but this method gets hard in the latest 5.1 version because the text seem to become falling apart. I can only recognise the video number like 5004 , 168 and "HCXY"(花车巡游 in Chinese) in the later text but I insist that it must includes 5.1 version key.

I have ever to use "fildder" to catch packs between server and client, some people said there is "FinishedParentQuestUpdateNotify" in the pack, however I have looked over all of the caught packs and cannot find this tag. It may be also encrypted!

So,what encrypt methods it could be so that it includes so many text pieces?
What can we do to get this file key to decrypt it?
And how can I get the original of the caught packs?

I have tried for the key for a few days (maybe a week long), and I feel so helpless now. I m a Nahida-lover and I really want to remain this "HCXY" video for my kawaii NahiWife. Why f**k mihoyo set too many f**k encrypts behind games?

**Comment by Deiloproxide** [comment]
Oh, I have knew this. You can decrypted it in "Assetstudio".
But, Emmm...it doesn't include any later key pieces.
The DDL of 5.1 main activity getting nearer, I'm concerned about whether we can catch the HCXY key in such limited time (about 3 days leave).

**Comment by ZzDaniel** [comment]
I'm trying something similar. Keeping an eye on it

**Comment by Deiloproxide** [comment]
@ZzDaniel
Oh , it's packet capture (pcap) , not catch pack , haha! (Because I'm a Chinese coder.)
I have ran some capture project and got these pcap file.
However it is still encrypted according https://sdl.moe/post/magic-sniffer/
Next , we should deal with it first.
For this , I have stayed over until 1:30 am for about a week , and I feel exhausted now.
[2024-11-05-09-43-45.json](https://github.com/user-attachments/files/17633955/2024-11-05-09-43-45.json)
[2024-11-05-09-44-45.json](https://github.com/user-attachments/files/17633957/2024-11-05-09-44-45.json)
[2024-11-05-09-45-07.json](https://github.com/user-attachments/files/17633960/2024-11-05-09-45-07.json)
Whether there are some experts can analyze these json?

**Comment by Deiloproxide** [comment]
@ZzDaniel
Oh , it's packet capture (pcap) , not catch pack , haha! (Because I'm a Chinese coder.)
I have ran some capture project and got these pcap file.
However it is still encrypted according https://sdl.moe/post/magic-sniffer/
Next , we should deal with it first.
For this , I have stayed over until 1:30 am for about a week , and I feel exhausted now.
[2024-11-05-09-43-45.json](https://github.com/user-attachments/files/17633955/2024-11-05-09-43-45.json)
[2024-11-05-09-44-45.json](https://github.com/user-attachments/files/17633957/2024-11-05-09-44-45.json)
[2024-11-05-09-45-07.json](https://github.com/user-attachments/files/17633960/2024-11-05-09-45-07.json)
Whether there are some experts can analyze these json?

**Comment by Deiloproxide** [comment]
[2024-11-05-09-43-45.json](https://github.com/user-attachments/files/17634028/2024-11-05-09-43-45.json)

**Comment by Deiloproxide** [comment]
@ToaHartor 
@ZzDaniel 
Yesterday night ,I called my friends to do this together and get some progress.
He wrote a program to analyze the xor key.
Finally , we got the xor key first 500 bytes (instead of someplace replaced by "xx")
(He said maybe it is enough.)
Next step is to get cmd id. (I really didn't know what it is.)
Different kinds of server (like mihoyo national server and hoyoverse international servers) has different cmd key.
<img width="465" alt="IMG_1488" src="https://github.com/user-attachments/assets/2c31a7aa-ebe8-4c85-88ab-236f3ddf5e9c">
![IMG_1491](https://github.com/user-attachments/assets/f43b7faf-25f1-4736-82a3-92b3799a9300)
<img width="469" alt="IMG_1490" src="https://github.com/user-attachments/assets/8a928fae-f00c-43d1-99fb-49658daaec58">

**Comment by ToaHartor** [comment]
CMDID tells you which packet corresponds to which action in the game, so that it uses the right protobuf structure to decode the packet. However if you are sure the packet you have is the right one (from [here](https://github.com/ToaHartor/GI-cutscenes/pull/27#issue-1308663377) it's either FinishedParentQuestNotify or FinishedParentQuestUpdateNotify), you might not even need it as the only interesting thing is the body, which can be decoded without a known structure, knowing the key is usually a uint64.

**Comment by Deiloproxide** [comment]
@ToaHartor 
Oh ! my teammate got the 5.1 HCXY (Nahida Birthday Activity) key. (but 5.1 other video key he didn't get yet , only these two videos.)


{
            "encAudio": true,
            "version": "5.1",
            "videoGroups": [
                {
                    "version": "15015",
                    "videos": [
                        "Cs_Natlan_LQ150150801_TLZL_Girl",
                        "Cs_Natlan_LQ150150801_TLZL_Boy",
                        "Cs_Fontaine_AQ40241601_SCBW_P1_Boy",
                        "Cs_Fontaine_AQ40241601_SCBW_P1_Girl",
                        "Cs_Fontaine_AQ40241601_SCBW_P2",
                        "ping_Girl",
                        "ping_Boy",
                        "Cs_Fontaine_AQ40241601_SCBW_P3_Boy",
                        "Cs_Fontaine_AQ40241601_SCBW_P3_Girl",
                        "Cs_Fontaine_AQ40241601_SCBW_P4",
                        "Cs_Fontaine_AQ40241601_SCBW_P5_Boy",
                        "Cs_Fontaine_AQ40241601_SCBW_P6",
                        "Cs_Fontaine_AQ40241601_SCBW_P5_Girl"
                    ]
                },
                {
                    "key": 9362292576596351,
                    "version": "40168",
                    "videos": [
                        "Cs_Sumeru_EQ401681801_HCXY_Boy",
                        "Cs_Sumeru_EQ401681801_HCXY_Girl"
                    ]
                },
                {
                    "version": "5012",
                    "videos": [
                        "Cs_Natlan_AQ50120901_MVBT"
                    ]
                },
                {
                    "version": "5011",
                    "videos": [
                        "Cs_Natlan_AQ50113101_BSSU_Boy",
                        "Cs_Natlan_AQ50113101_BSSU_Girl"
                    ]
                },
                {
                    "version": "5013",
                    "videos": [
                        "Cs_Natlan_AQ50131101_AWFN_Boy",
                        "Cs_Natlan_AQ50131101_AWFN_Girl"
                    ]
                }
            ]
        }


Pls update the version.json
However , the activity has been end , but we can still download the video assets at #104 .

**Comment by lrastar** [comment]
![image](https://github.com/user-attachments/assets/220dfc66-6319-4e7f-8f5b-1cd0afc17608)
![image](https://github.com/user-attachments/assets/35e12f99-9d38-4d30-84a6-c67d79b24fdf)
Why is there still an error when decrypting "Cs_Sumeru_EQ401681801_HCXY_Girl"? 
Is my .json file filled in incorrectly?
 (Sorry for the machine translation)

**Comment by Deiloproxide** [comment]
> ![image](https://private-user-images.githubusercontent.com/143856673/384558738-220dfc66-6319-4e7f-8f5b-1cd0afc17608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMTYxNzAsIm5iZiI6MTczMTExNTg3MCwicGF0aCI6Ii8xNDM4NTY2NzMvMzg0NTU4NzM4LTIyMGRmYzY2LTYzMTktNGU3Zi04ZjViLTFjZDBhZmMxNzYwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwMTMxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWU4NDAxMTVlMWZkZTI0MzFlMjZlZmNjMGY4NTRkZjI1NzIwY2RjNjFlNGViMDAxNmI1ZDc1YTA3OTI4YjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lE0xzoaiHfRRIuY1vRCwJX3JwJLMYAje1LSj6vADzv8) ![image](https://private-user-images.githubusercontent.com/143856673/384558847-35e12f99-9d38-4d30-84a6-c67d79b24fdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMTYxNzAsIm5iZiI6MTczMTExNTg3MCwicGF0aCI6Ii8xNDM4NTY2NzMvMzg0NTU4ODQ3LTM1ZTEyZjk5LTlkMzgtNGQzMC04NGE2LWM2N2Q3OWIyNGZkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwMTMxMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDdiYjFlZTY1YjAzYjVmMjk5ZjYxOGU3MDEwMDBiMWY3MGVlYWJjYjQ0MDA2ZDQ3OTQwYTEwMWYzM2FmY2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7ERIQ0HHBHPNvQJ1iPQ-7BorTF0gsun_lB4jeXwA0fA)为什么解密 “Cs_Sumeru_EQ401681801_HCXY_Girl” 时仍然报错？我的 .json 文件填写错误吗？ （抱歉机器翻译）

@lrastar 

Oh ! It's json compiling error , pls check your json bracket format before you run the program.

![屏幕截图 2024-11-09 094127](https://github.com/user-attachments/assets/f52cf082-2787-4387-965a-1e89013cf624)


There are six brackets at the json end.
I copied it from my json , and I finally decrypted it.
(And I only copied the content between a pair of brackets.)
[versions.json](https://github.com/user-attachments/files/17685544/versions.json)

Plus , you needn't translate it into Chinese . I can understand English , haha !

**Comment by ToaHartor** [comment]
Thank you for your hard work ! The key will be added once all keys for this version are found, but it can still be added manually to `versions.json` for those who want to decrypt the newer files. Btw, if you were able to write a small guide detailing the process to retrieve a key, it would greatly help the search to get the keys (and since I no longer play the game, I don't really keep in touch with all the changes so I'm not aware of the new solutions, but I know people who still play that could help retrieving them).

**Comment by moux23333** [comment]
这里提醒一下，CN和OS的cmdid都是一样的，没有区别，区别在于版本号，比如5.0.0 5.1.0互不相同。
顺带一提，cmdid在解析数据包可能并不是必需的，因为前些版本的key都是在没有proto和cmdid的情况下进行抓包并解析。
关于5.1.0的key我会在这几天内提交pr。

**Comment by moux23333** [comment]
blk中早在2.7以后就不存在任何key了，全部交由服务器发包解密，blk仅负责归类

**Comment by Hitachi-Momoka** [comment]
今天5.2更新包出了，发现的更新内容会删除纳西妲生日的过场动画，建议备份起来。

**Comment by Hitachi-Momoka** [comment]
> ![image](https://private-user-images.githubusercontent.com/143856673/384558738-220dfc66-6319-4e7f-8f5b-1cd0afc17608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MDkxNzAsIm5iZiI6MTczMTkwODg3MCwicGF0aCI6Ii8xNDM4NTY2NzMvMzg0NTU4NzM4LTIyMGRmYzY2LTYzMTktNGU3Zi04ZjViLTFjZDBhZmMxNzYwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwNTQ3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjEyNmVhZTA0YzU5ZjZiMDNjZTkyOTkzYmUyZDI1YzNkNjJhMzkxMTBmYmNmMDhmZjU3MTNmY2UwYjJkNjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GN0-SvytsYA-QLUQWkconrGiP5eY9URBuGENJgeKins) ![image](https://private-user-images.githubusercontent.com/143856673/384558847-35e12f99-9d38-4d30-84a6-c67d79b24fdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MDkxNzAsIm5iZiI6MTczMTkwODg3MCwicGF0aCI6Ii8xNDM4NTY2NzMvMzg0NTU4ODQ3LTM1ZTEyZjk5LTlkMzgtNGQzMC04NGE2LWM2N2Q3OWIyNGZkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwNTQ3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzA2YTc3MDc2ODBkOGM3YTVjYTRjNTYzZGZhYWUxZGY5Zjg4YzU2ZjY4MmMwM2FhYzQ4YzFmOTg4NzM4YTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MobHmEUutIk5O1CrwKo6K5ziTxHTwBVnGW3OWMu6GS0) Why is there still an error when decrypting "Cs_Sumeru_EQ401681801_HCXY_Girl"? Is my .json file filled in incorrectly? (Sorry for the machine translation)

试了一下，纳西妲生日过场动画是可以正常解出来的。
![QQ20241118-135104](https://github.com/user-attachments/assets/0b6194db-7183-40a4-aaf7-b1b52dd13d00)
![QQ20241118-135208](https://github.com/user-attachments/assets/cf81f0a5-b4fc-4d2c-bccd-9bd3f34821e8)

**Comment by ToaHartor** [comment]
Closing this issue as 5.1 keys have been added, however I'll pin this issue in order to allow people to find the process more quickly. Thank you for your work !
