### ISSUE TITLE
Add keys from Pre-Beta versions

### ISSUE THREAD

**Issue by JPS46225** [ToaHartor/GI-cutscenes#18]
Hi

I was wondering if the keys from the pre-beta versions could be added?

Thanks

**Comment by ToaHartor** [comment]
If you're talking about 2.8 beta, the keys for this version aren't in the file at the root of the cutscenes folder (and also confirms that the 2.7 keys aren't there as well). The only way I know to get them would be to actually have a beta account and to dump the packets of the game. There might be some other ways, but I don't really know them.

However, I think I will soon update the README file saying that the pull requests were open if some people already dumped them.

**Comment by JPS46225** [comment]
Hi

I'm talking about pre 1.0 :)

I wanna try and get the old opening cutscene from the start of the game.

**Comment by ToaHartor** [comment]
Oh sorry I misunderstood. Concerning the three CBT, the first one didn't have any encryption or muxing (the cutscenes were only in the mp4 format), the second one had USM files but weren't encrypted (only demuxing was required), and the third one have the same key system than the live release.

**Comment by JPS46225** [comment]
Oh cool. I'll close this then :)

**Comment by Unknow-404** [comment]
> Hi
> 
> I'm talking about pre 1.0 :)
> 
> I wanna try and get the old opening cutscene from the start of the game specifically.
> 
> Maybe the key for this one can be brute forced since it's so early in development?

Can you share the old cutscenes file with me? Thank you so much.

**Comment by FanJZSS** [comment]
Can you tell me where I can download the Pre-Beta versions? I can only find version 1.3 at most.:(

**Comment by JPS46225** [comment]
> Can you tell me where I can download the Pre-Beta versions? I can only find version 1.3 at most.:(

https://gist.github.com/AquaPlaysYT/ae8d3e5e341007752a625d7eeccf9580

**Comment by FanJZSS** [comment]
> > Can you tell me where I can download the Pre-Beta versions? I can only find version 1.3 at most.:(
> 
> https://gist.github.com/AquaPlaysYT/ae8d3e5e341007752a625d7eeccf9580

Thank you very much.
