### ISSUE TITLE
Hope it can edit ffmpeg options

### ISSUE THREAD

**Issue by Unknow-404** [ToaHartor/GI-cutscenes#19]
Will the next version support edit fffmpeg options?

**Comment by ToaHartor** [comment]
Can you give me some examples and use cases ? I don't know ffmpeg well enough to see if some could require a special treatment.

However I can see some ways of doing that (within the config file and directly in the command line)

**Comment by Unknow-404** [comment]
> > Can you give me some examples and use cases ? I don't know ffmpeg well enough to see if some could require a special treatment.
> > However I can see some ways of doing that (within the config file and directly in the command line)
> 
> I modified line 105 of [src/Mergers/FFMPEG.cs] file again and built the client, which will convert the extracted video to H264 encoding and audio to AAC encoding.

_command += $" -vcodec libx264 -acodec aac -ab 256k \"{_output}\"";

**Comment by Unknow-404** [comment]
If I directly copy the source code (VP9), there will be a splash screen when playing.

**Comment by Unknow-404** [comment]
The reason why I want to re encode the video is that using H.264 and AAC encoding can make the video play on most devices.

**Comment by Unknow-404** [comment]
Thanks for your reply!

**Comment by ToaHartor** [comment]
Added in the PR #57 as command arguments
