### ISSUE TITLE
help тwт

### ISSUE THREAD

**Issue by gelik1html** [ToaHartor/GI-cutscenes#20]
everything seems to be correct, but maybe I misunderstood how to do it (sorry, I don't know how to do this very well)
![pRuNreKEBS](https://user-images.githubusercontent.com/105743029/178140581-ba344a73-a977-4574-9733-4eafb7579074.png)

**Comment by ToaHartor** [comment]
This error seems to be caused by the format of the JSON config. Could you please send me the content of the file `appsettings.json` to see if the format is correct ?

**Comment by gelik1html** [comment]
:p
![notepad++_OMBrle3rlM](https://user-images.githubusercontent.com/105743029/178145006-c9a98312-8630-4590-9845-9fcd7a6c6b7e.png)

**Comment by Unknow-404** [comment]
> :p ![notepad++_OMBrle3rlM](https://user-images.githubusercontent.com/105743029/178145006-c9a98312-8630-4590-9845-9fcd7a6c6b7e.png)

Edit the file location:
`C:\\MKVToolNox`
And it must be accurate to the EXE file.

**Comment by Unknow-404** [comment]
> :p ![notepad++_OMBrle3rlM](https://user-images.githubusercontent.com/105743029/178145006-c9a98312-8630-4590-9845-9fcd7a6c6b7e.png)

At the same time, you should use the [--engine] option to use the custom engine when exporting.

**Comment by gelik1html** [comment]
thanks! everything is working :з
