### ISSUE TITLE
About key issues

### ISSUE THREAD

**Issue by Unknow-404** [ToaHartor/GI-cutscenes#21]
Would you please tell me how to get the key of the USM file?

**Comment by phuchptty** [comment]
From 2.0 to 2.6, keys are store in 26236578.blk file (you can find it in "_Path to your genshin drive\Genshin Impact game\GenshinImpact_Data\StreamingAssets\VideoAssets_").

However, you need a special tool to decrypt it. I suggest to check out [khang06/genshinblkstuff](https://github.com/khang06/genshinblkstuff). I had "dumped" it from the 2.8 preload which was released yesterday. You can check it here: https://anotepad.com/notes/xm2jiiks

From 2.7, there are multiple keys for multiple files. And the key to decrypt that cutscene will be sent from server when the client need it. Check out [repo owner's comment](https://github.com/ToaHartor/GI-cutscenes/issues/8#issuecomment-1146618993) for more info

**Comment by Unknow-404** [comment]
Thanks a lot
