### ISSUE TITLE
How to get the 2.8 cutscene keys?

### ISSUE THREAD

**Issue by Unknow-404** [ToaHartor/GI-cutscenes#24]
![image](https://user-images.githubusercontent.com/51278893/178733183-bbcd0b39-1c0b-446b-9cef-ef949e364030.png)

**Comment by Unknow-404** [comment]
![image](https://user-images.githubusercontent.com/51278893/178733057-b07bcc35-4a4e-4f42-b98d-d8f396765e40.png)

**Comment by phuchptty** [comment]
Because the key will send from the server. There is no way to get from the client. You must wait until that event happens.
Or you can brute force 16 char key length (around 10^16 case)

**Comment by Unknow-404** [comment]
> Because the key will send from the server. There is no way to get from the client. You must wait until that event happens.
> Or you can brute force 16 char key length (around 10^16 case)

Can I get the key by intercepting the API address?

**Comment by phuchptty** [comment]
> > Because the key will send from the server. There is no way to get from the client. You must wait until that event happens.
> > Or you can brute force 16 char key length (around 10^16 case)
> 
> Can I get the key by intercepting the API address?

Yes. But not at this time. The only way is to wait for mhy release event. Or you have a dump network packet from beta tester (Well impossible)

**Comment by Unknow-404** [comment]
Thanks for your reply.

> > > Because the key will send from the server. There is no way to get from the client. You must wait until that event happens.
> > > Or you can brute force 16 char key length (around 10^16 case)
> > 
> > 
> > Can I get the key by intercepting the API address?
> 
> Yes. But not at this time. Like I was said, the only way is to wait for mhy release event. Or you have a dump network packet from beta tester (Well impossible tbh)

Thanks for your reply.
