### ISSUE TITLE
Checking invalid key

### ISSUE THREAD

**Issue by phuchptty** [ToaHartor/GI-cutscenes#25]
Is there any way to check whether the key is invalid or not?
Ex: demuxUsm allows A and B keys, how do we know those keys are valid and will demux succeed.

**Comment by ToaHartor** [comment]
Since the demuxing stage only applies a mask to the tracks, without affecting their headers, I would think the only way to know if it succeeded is to play the file.

**Comment by phuchptty** [comment]
Thanks for the reply. So it's impossible atm
