### ISSUE TITLE
Would you interest in Honkai Impact 3rd cutscenes?

### ISSUE THREAD

**Issue by LainHE** [ToaHartor/GI-cutscenes#29]
I  think the Honkai Impact 3rd cutscenes are also encrypted from version 5.9. Would you interest in Honkai Impact 3rd cutscenes?

**Comment by ToaHartor** [comment]
I don't really know how their encryption look like since I'm not playing HI3 and I don't have the files, however there are some points to note :

- USM is a proprietary format, made by Criware. Therefore, I doubt the encryption would differ from Genshin, which means that if you have the keys then you should be able to decrypt those files (or at least the video)
- About the audio, two kind of encryption exist : one that comes with the USM format and works similarly to the video encryption, and one that comes with the audio format itself (ADX/HCA, etc. For instance, Genshin only uses the second one). The second one is already implemented in this tool, however the first one requires some testing samples (which I don't have).

To be honest, I'm interested in how it would work (especially if it requires additional support for track decryption in the USM format or for merging with subtitles), but I won't go hunting the keys if it requires playing the game **and** if every USM has a different key (like it's now the case in Genshin). However, I might have a motivation spike if I start playing 👀. 

This also apply to Honkai Star Rail, which iirc also uses the same file format and only has the video encrypted.

**Comment by ZenitHTH** [comment]
honkai impacrt 3 can use VGMtoolbox to decrypted usm file , but it suck

**Comment by LainHE** [comment]
>@ZenitHTH honkai impacrt 3 can use VGMtoolbox to decrypted usm file (video is not corrupt) , but it suck because it split audio and video file and not have subtitle file

It's changed from version 5.9. before 5.8 or earlier version, those files are just mp4 files. from version 5.8, they are changed into USM files but not encrypt. However, the cutscens from 5.9 are all encrypted. In other words, the video from 5.9 are corrupted after decode.

**Comment by LainHE** [comment]
>@ToaHartor I don't really know how their encryption look like since I'm not playing HI3 and I don't have the files, however there are some points to note :
> 
> * USM is a proprietary format, made by Criware. Therefore, I doubt the encryption would differ from Genshin, which means that if you have the keys then you should be able to decrypt those files (or at least the video)
> * About the audio, two kind of encryption exist : one that comes with the USM format and works similarly to the video encryption, and one that comes with the audio format itself (ADX/HCA, etc. For instance, Genshin only uses the second one). The second one is already implemented in this tool, however the first one requires some testing samples (which I don't have).
> 
> To be honest, I'm interested in how it would work (especially if it requires additional support for track decryption in the USM format or for merging with subtitles), but I won't go hunting the keys if it requires playing the game **and** if every USM has a different key (like it's now the case in Genshin). However, I might have a motivation spike if I start playing 👀.
> 
> This also apply to Honkai Star Rail, which iirc also uses the same file format and only has the video encrypted.

You could try Honkai Impact 3rd, the plot is sweet.

Before, the verison 5.8, those videos are just mp4 files. They are converted and encrypted into USM files from 5.9 (5.8 and early videos are just convert into USM files but not encrypt). Therefore, I believe Honkai uses same way of Genshin.

If you want, I could send you usm files. There are many beautiful CGs.

**Comment by phuchptty** [comment]
Guys. Honkai will update next week (maybe Tuesday or Wednesday). After that, we will figure out whether keys will send from the server or hard coded in a file. Because honkai structures are sucked so it may be hard to find.

**Comment by LainHE** [comment]
> Guys. Honkai will update next week (maybe Tuesday or Wednesday). After that, we will figure out whether keys will send from the server or hard coded in a file. Because honkai structures are sucked so it may be hard to find.

Is there any good news? @phuchptty

**Comment by phuchptty** [comment]
> > Guys. Honkai will update next week (maybe Tuesday or Wednesday). After that, we will figure out whether keys will send from the server or hard coded in a file. Because honkai structures are sucked so it may be hard to find.
> 
> Is there any good news? @phuchptty

Hmm. I checked 5.9 CG but I didn't see any encrypted video. Just a normal usm package

**Comment by LainHE** [comment]
Okay... Which server and platform of HI3rd do you use? I've been playing on PC's Chinese server. I tried to download the glb server one, and I can't extract any single one readable file.

I am just using VGMToolbox to extract USM files. Is that too old? It just works with all CGs before v5.9 on Chinses server.

Do you have any personal contact information? It may not be appropriate to continue to communicate here...

**Comment by phuchptty** [comment]
> Okay... Which server and platform of HI3rd do you use? I've been playing on PC's Chinese server. I tried to download the glb server one, and I can't extract any single one readable file.
> 
> I am just using VGMToolbox to extract USM files. Is that too old? It just works with all CGs before v5.9 on Chinses server.
> 
> Do you have any personal contact information? It may not be appropriate to continue to communicate here...

I using SEA version on windows

**Comment by LainHE** [comment]
> > Okay... Which server and platform of HI3rd do you use? I've been playing on PC's Chinese server. I tried to download the glb server one, and I can't extract any single one readable file.
> > I am just using VGMToolbox to extract USM files. Is that too old? It just works with all CGs before v5.9 on Chinses server.
> > Do you have any personal contact information? It may not be appropriate to continue to communicate here...
> 
> I using SEA version on windows

I tried SEA one but no use. Here is the recording what I did. https://youtu.be/xpaN1PwPw3o
All m2v files from SEA could not open. And the m2v files from Chinese version is what I told before.
Did I do anything wrong?

**Comment by phuchptty** [comment]
Okay, I see. There is some problem with VLC. It can't decode demux video m2v format.
I converted to mp4 using FFmpeg and now it can open completely

**Comment by LainHE** [comment]
Oh.. I get it now. Thank you very much. Sorry for wasting your time.
