### ISSUE TITLE
is there a way to exhaustive brute-force decrypt keys?

### ISSUE THREAD

**Issue by unknown10777** [ToaHartor/GI-cutscenes#34]

**Comment by phuchptty** [comment]
Yes. The Key is 16 characters in length with text and number. With 10 numbers and 26 characters, you will have 36^16 cases.
It takes about 8-10 years to complete and you need to watch 36^16 videos output. Ofc you can train an AI to help you with it.
~~Or buy a quantum computer~~

**Comment by People-11** [comment]
is possible.
