### ISSUE TITLE
When will update new CGs in ver3.0

### ISSUE THREAD

**Issue by SUNJY15** [ToaHartor/GI-cutscenes#35]
Four new CGs now released in ver3.0 of Genshin.
Hope update asap

**Comment by phuchptty** [comment]
hope soon

**Comment by Liujunhua007** [comment]
+1

**Comment by ToaHartor** [comment]
Please check #36, you'll be happy.

**Comment by ToaHartor** [comment]
Closing this as 3.0 keys have been added.
