### ISSUE TITLE
Can I convert audio tracks to other format ( eg. opus ) to save some storage before merging to mkv?

### ISSUE THREAD

**Issue by CarterLi** [ToaHartor/GI-cutscenes#40]
I'm using ffmpeg. Some info I found https://askubuntu.com/questions/211054/how-to-convert-a-sound-file-to-opus

https://github.com/ToaHartor/GI-cutscenes/blob/main/src/Mergers/FFMPEG.cs#L73

**Comment by Unknow-404** [comment]
See #19.

**Comment by CarterLi** [comment]
-acodec libopus -ab 256k -vcodec copy
