### ISSUE TITLE
Sumeru cutscenes seem be broken

### ISSUE THREAD

**Issue by FlysoftBeta** [ToaHartor/GI-cutscenes#46]
![image](https://user-images.githubusercontent.com/49718840/193589033-51aa8867-f2a1-4244-a4b7-355f5f7ae322.png)

**Comment by Unknow-404** [comment]
[3.1 keys except activity](https://github.com/ToaHartor/GI-cutscenes/blob/17d04116ea02aaf64f36fb0b08165234e8fd380f/versions.json)

**Comment by Unknow-404** [comment]
It seems used the wrong key.

**Comment by FlysoftBeta** [comment]
thanks, I will have a try.

**Comment by FlysoftBeta** [comment]
thanks a lot! it works fine now.

**Comment by FlysoftBeta** [comment]
please consider merging this branch to the main branch.
