### ISSUE TITLE
为什么我打开GICutscenes会闪退

### ISSUE THREAD

**Issue by YOYSALENGLI** [ToaHartor/GI-cutscenes#50]
我打开GICutscenes它出现了以下情况:
Required command was not provided.

Description:
  A command line program playing with the cutscenes files (USM) from Genshin Impact.

Usage:
  GICutscenes [command] [options]

**Comment by ToaHartor** [comment]
If you executed the program without any argument, it will throw an error as no command corresponds to "no arguments". I might be wrong but I believe it's the default behaviour of the CLI library provided by Microsoft used in this program. But maybe there is a way to not throw it, which I'm not aware of.

Did it solve your issue ?

**Comment by Unknow-404** [comment]
> 我打开GICutscenes它出现了以下情况:
> Required command was not provided.
> 
> Description:
>   A command line program playing with the cutscenes files (USM) from Genshin Impact.
> 
> Usage:
>   GICutscenes [command] [options]

Maybe you didn't give it a command.

**Comment by YOYSALENGLI** [comment]
那我该怎么给它一个命令

**Comment by Unknow-404** [comment]
> 那我该怎么给它一个命令

You could read the [README.md](https://github.com/ToaHartor/GI-cutscenes/blob/main/README.md) to get more help.

**Comment by YOYSALENGLI** [comment]
好了，原来是我没下载GICutscenesUI.exe，就直接去运行GICutscenes.exe才会发生以上错误，问题已解决，谢谢!
