### ISSUE TITLE
UID

### ISSUE THREAD

**Issue by handi92** [ToaHartor/GI-cutscenes#64]
Is possible to show UID number?

**Comment by Unknow-404** [comment]
If you want to show your UID, please record the cutscene in the game.

**Comment by ToaHartor** [comment]
If you really want to show your UID without recording the game, you have two options :
- Creating a custom subtitle file with your UID positioned in the lower right corner and burn the subtitles in the video using ffmpeg.
- Modify the current subtitles, and add the UID at the right position. This way, it won't be burned in the video and can be removed like the subtitles.

But I don't think it will be an implemented option in the future, as you could simply record the game.
