### ISSUE TITLE
Didnt extract all cutscenes

### ISSUE THREAD

**Issue by DenySVK1** [ToaHartor/GI-cutscenes#65]
Hi I tried the new version because they added summeru but not all cutscenes were extracted.
(https://user-images.githubusercontent.com/61192651/202874094-dbbf9236-25d7-4fa1-ad38-e3ab17451819.png)

**Comment by phuchptty** [comment]
Your `version.json` isn't update to date.

Get a new one from here: https://github.com/ToaHartor/GI-cutscenes/blob/main/versions.json

**Comment by DenySVK1** [comment]
Thank you problem solved
