### ISSUE TITLE
[General question] How to get encryption keys from new cutscenes

### ISSUE THREAD

**Issue by nicholasyoannou** [ToaHartor/GI-cutscenes#69]
Would like to ask, thanks so much for this tool but there's been a new update with a few new cutscenes that I wanna do a little sneakpeak. Problem is how on earth do you retrieve the encryption keys?

**Comment by gszshdzz** [comment]
#66

**Comment by mrwan200** [comment]
See https://github.com/ToaHartor/GI-cutscenes/issues/24#issuecomment-1183596024

**Comment by phuchptty** [comment]
https://github.com/ToaHartor/GI-cutscenes/issues/8#issuecomment-1146618993
or
https://github.com/ToaHartor/GI-cutscenes/pull/27#issue-1308663377
