### ISSUE TITLE
Cs_YLLQ1012008_EulaShow.usm still no key

### ISSUE THREAD

**Issue by BiosNod** [ToaHartor/GI-cutscenes#70]
Cs_YLLQ1012008_EulaShow.usm still no key

Was added in version 1.5 and was removed in version 1.6

**Comment by Unknow-404** [comment]
The key is default: `0`

**Comment by Unknow-404** [comment]
You can add `Cs_YLLQ1012008_EulaShow` to the version `common`.

**Comment by ToaHartor** [comment]
I didn't expect that people would try to decrypt it, but I can add that to `versions.json`.

**Comment by phuchptty** [comment]
it seem an event cutscene

**Comment by ToaHartor** [comment]
It's a cutscene that was from back in 1.5, that was later removed in 1.6. Basically inside there are only drafts of the cutscene in Eula's character quest. It was initially intended to be pre-rendered but they changed their minds during the process.

**Comment by BiosNod** [comment]
> The key is default: `0`

Oh okay, sorry, very easy solution 

PR: https://github.com/ToaHartor/GI-cutscenes/pull/74

**Comment by Unknow-404** [comment]
`Cs_YLLQ1012008_EulaShow` is an unfinished cutscene like this:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/51278893/209565366-1cfd49e5-9df4-45f5-9b02-5c447adf2729.png">
