### ISSUE TITLE
关于字幕

### ISSUE THREAD

**Issue by duanxiaosheng** [ToaHartor/GI-cutscenes#72]
![image](https://user-images.githubusercontent.com/48898646/209475349-110f3e35-82d5-4e38-bf04-f469f2beae2c.png)
字幕样式可以支持修改吗，字幕的黑边不太好看

**Comment by Unknow-404** [comment]
You can choose to render your own subtitles.

**Comment by duanxiaosheng** [comment]
@Unknow-404 太感谢你的回复了，有具体的操作视频或步骤吗，早上看了 [关于字幕大小](https://github.com/ToaHartor/GI-cutscenes/issues/41)，我不是太懂这个东西。具体不会搞。或者添加个联系方式。

**Comment by ToaHartor** [comment]
This style looks like the default one when the font is missing. Have you included the game font in the main folder ? (you can check [this section] (https://github.com/ToaHartor/GI-cutscenes#managing-the-font-files) that tells you where to get them, then copy them in the root folder of the tool)

**Comment by duanxiaosheng** [comment]
@ToaHartor 
这两个字体文件是已经复制过来之后 导出的视频字幕还是上面图片那样
![image](https://user-images.githubusercontent.com/48898646/209516774-191249a7-76af-4957-95ed-dac68345f31e.png)

**Comment by duanxiaosheng** [comment]
@ToaHartor 
![image](https://user-images.githubusercontent.com/48898646/209532614-d4a5e7b3-c296-4fbd-abd2-f5f0011be0e3.png)
如果想要做到这种字幕效果我应该怎么做

**Comment by ToaHartor** [comment]
> @ToaHartor 这两个字体文件是已经复制过来之后 导出的视频字幕还是上面图片那样 ![image](https://user-images.githubusercontent.com/48898646/209516774-191249a7-76af-4957-95ed-dac68345f31e.png)

Those two files are the font files in the game. They are placed in the right folder on the picture.

> @ToaHartor ![image](https://user-images.githubusercontent.com/48898646/209532614-d4a5e7b3-c296-4fbd-abd2-f5f0011be0e3.png) 如果想要做到这种字幕效果我应该怎么做

When you use the program, if it doesn't find the font, it should prompt you `ja-jp.ttf font not found, skipping...` or `zh-cn.ttf font not found, skipping...`. If it doesn't print you that in the console, then the problem might be elsewhere.

The current version of the program has bigger subtitles, but the same font than the ones appearing in the "Custom style" of this picture. The "Custom style" will be included in the next version.

**Comment by duanxiaosheng** [comment]
> > @ToaHartor 这两个字体文件是已经复制过来之后 导出的视频字幕还是上面图片那样 ![图像](https://user-images.githubusercontent.com/48898646/209516774-191249a7-76af-4957-95ed-dac68345f31e.png)
> 
> 这两个文件是游戏中的字体文件。它们放置在图片的右侧文件夹中。
> 
> > @ToaHartor ![图像](https://user-images.githubusercontent.com/48898646/209532614-d4a5e7b3-c296-4fbd-abd2-f5f0011be0e3.png) 如果想要做到这种字幕效果我应该怎么做
> 
> 当您使用该程序时，如果找不到字体，它应该会提示您。如果它没有在控制台中打印出来，那么问题可能出在其他地方。`ja-jp.ttf font not found, skipping...``zh-cn.ttf font not found, skipping...`
> 
> 该程序的当前版本具有更大的字幕，但字体与此图片的“自定义样式”中显示的字体相同。“自定义样式”将包含在下一个版本中。

非常感谢那我就期待下一个版本。辛苦了
