### ISSUE TITLE
Key dumping starting version 2.7

### ISSUE THREAD

**Issue by ToaHartor** [ToaHartor/GI-cutscenes#8]
From version 2.0 until version 2.6, the second key for the cutscenes of the current version was available in the dispatch's encrypted config, which was quite easy to retrieve.

However starting version 2.7, the second keys might now be sent when the game needs it, therefore either in a packet at the beginning of a cutscene during a quest or during the login. The version file (right below) also gives the several groups of cinematics that have the same second key. It would then require a rigorously taken packet capture to get the key associated with the cutscene viewed.

```json
"videoGroups": [
	{
		"version": "1031",
		"videos": [
			"Cs_LiYue_LQ10310301_BreakThroughSpace_Boy",
			"Cs_LiYue_LQ10310301_BreakThroughSpace_Girl",
			"Cs_LiYue_LQ10310601_FusheStory"
		]
	},
	{
		"version": "11026",
		"videos": [
			"Cs_LiYue_LQ110261501_YelanStory_Boy",
			"Cs_LiYue_LQ110261501_YelanStory_Girl"
		]
	}
]
```

There's a strong probability that, like for the previous versions, they would give the keys in the Video Versions file (as the code would suggest). So, to get the keys from 2.7, we would have to wait for the 2.8 release.
Until 2.8 drops, I'll try to verify my theory....

**Comment by SuperZombi** [comment]
Can u ping me pls, when you get a key for 2.7 (Hope it doesnt take a whole month xD)

**Comment by ToaHartor** [comment]
Currently working on it, the file `versions.json` will be updated as soon as I get the new keys

**Comment by SuperZombi** [comment]
@ToaHartor  If you want, i can help you to make UI on Python for this app

**Comment by ToaHartor** [comment]
I still don't know about a GUI option to be honest, maybe in the future.

**Comment by SuperZombi** [comment]
> I still don't know about a GUI option to be honest, maybe in the future.

Look what I have already done [in developing]


![image](https://user-images.githubusercontent.com/75096786/171937726-2eabb49d-705e-4b10-a483-800540a9eb43.png)

**Comment by SuperZombi** [comment]
@ToaHartor  Hey check this:
https://github.com/SuperZombi/GICutscenesUI

**Comment by ToaHartor** [comment]
That's clean ! I will link your repository here

**Comment by ToaHartor** [comment]
Update on this : the PR #11 made it clear, the key is given in one of the packets, named `FinishedParentQuestNotify`, obfuscated field `GJJJKEIPAPC` (was a bit late on this, since I haven't done the quests yet)

**Comment by SuperZombi** [comment]
Can anyone draw an icon for programm?

**Comment by ToaHartor** [comment]
Closing this issue, as the data has been verified

**Comment by 4vent** [comment]
How can packets be monitored? Software to use? I am interested in getting the latest version, 3.8 code on my own.
