### ISSUE TITLE
3.4 keys update pls

### ISSUE THREAD

**Issue by ZhuHuan521** [ToaHartor/GI-cutscenes#80]
pls update 3.4 keys

**Comment by Unknow-404** [comment]
3.4 keys has already updated, you can get the latest versions.json file [here](https://github.com/ToaHartor/GI-cutscenes/blob/8dbf089c6723dd09731048171597c7bbf9e854c7/versions.json).

**Comment by ToaHartor** [comment]
The file has been updated in the current repository.
