### ISSUE TITLE
May I extract Jean's cutscenes with old-version clothing in current client?

### ISSUE THREAD

**Issue by jxworld** [ToaHartor/GI-cutscenes#87]
Hi @ToaHartor ,
Thank you for your efforts very much.
As you know, I'm a crazy fan of Jean in China. The replacement of Jean's clothing has blown my mind.
I really want to rewatch the Jean's cutscenes with old-version clothing in 1.0 version.
Is there any possibility to extract Jean's cutscenes with old-version clothing in current client?
or you might have the client before version 2.1(in that time the clothes is not replaced)

Thank you very much!
Might you have a nice day
Wu shiuathie

**Comment by Unknow-404** [comment]
You should download the old-version's full data first.

**Comment by Unknow-404** [comment]
And this tool can only extract the USM file.

**Comment by jxworld** [comment]
@Unknow-404 thank you for your reply, I'm trying to find the old-version client, but all I have is the installer.
I have no idea whether it can correctly install without internet (ensure there is no upgrade in the client)
Now, I'm downloading, waiting for it ...

**Comment by jxworld** [comment]
I have made it. Thank you very much @ToaHartor @Unknow-404.
