### ISSUE TITLE
More clips quality 

### ISSUE THREAD

**Issue by SuperZombi** [ToaHartor/GI-cutscenes#9]
Is it possible to get clips in better quality (60fps)?. Because all clips are in 30fps now. Or this isn't possible, due to the fact that these are pre-rendered videos?

**Comment by ToaHartor** [comment]
This tool only extracts the original video file from the USM, so you'll be getting the cutscene like it was originally pre-rendered, so in 30fps.
`mkvmerge` (the software used to merge the files) is unable to add those frames, as it would require to completely re-encode the video track. In my opinion, it's not part of what this tool can do (and will do in the future), as it aims to extract the files to remain the closest to the original files, only making them easier to read.

However, if you wish to add frames to it, you can use another tool (ffmpeg) to re-encode the video (see https://stackoverflow.com/questions/60997945/reencode-videos-from-30fps-to-60fps-using-ffmpeg)
