### ISSUE TITLE
请问星穹铁道的usm文件，能使用这个程序获得吗

### ISSUE THREAD

**Issue by huaxianmfs** [ToaHartor/GI-cutscenes#99]

**Comment by BUnipendix** [comment]
不能

**Comment by huaxianmfs** [comment]
> 不能

其实在开服的时候，我试过了，确实不能。我本来想问的其实是对铁道的cg有什么头绪吗？
不知道为什么就写成了那个标题

**Comment by BUnipendix** [comment]
这里是原神的视频解包工具，不是星穹铁道的，建议不要在这里提问，不过给你提个醒，铁道和原神都是使用加密的CRI USM视频文件，至于密钥自己找。

**Comment by huaxianmfs** [comment]
> 这里是原神的视频解包工具，不是星穹铁道的，建议不要在这里提问，不过给你提个醒，铁道和原神都是使用加密的CRI USM视频文件，至于密钥自己找。

好吧，谢谢，我认为在找钥匙之前，还得找到钥匙孔。相信时间会给我答案的。

**Comment by SuperScript-PRC** [comment]
> 这里是原神的视频解包工具，不是星穹铁道的，建议不要在这里提问，不过给你提个醒，铁道和原神都是使用加密的CRI USM视频文件，至于密钥自己找。

本人试过吧，星穹铁道(Homkai Star Rail)的确实是用不了这个来解密USM文件

**Comment by SuperScript-PRC** [comment]
> > 这里是原神的视频解包工具，不是星穹铁道的，建议不要在这里提问，不过给你提个醒，铁道和原神都是使用加密的CRI USM视频文件，至于密钥自己找。
> 
> 本人试过吧，星穹铁道(Homkai Star Rail)的确实是用不了这个来解密USM文件

`System.Collections.Generic.KeyNotFoundException: Unable to find the second key in versions.json for CS_ChapLoop02_Act0130`； 但是可以发现这两款游戏因为都是一个公司做的应该有很多共通点比如pck文件格式都是一模一样的，星穹铁道的usm格式一定只是做了一点小改动，希望仓库主能适配一下

**Comment by ToaHartor** [comment]
As I said in #113, the video format is the same than for Genshin, so only the key has to be found (which may be difficult). We still don't know if there are two separated keys (one calculated with an algorithm and a fixed one) that are merged together, or only one like in the early stages of Genshin. Still, once you have the key, you should be able to decrypt the video.

**Comment by muimuiYoHo** [comment]
key还更新吗
